services:
  db:
    image: postgres:16-alpine
    container_name: wallet-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wallet
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: wallet-api
    restart: always
    ports:
      - '3001:3001'
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/wallet
      JWT_SECRET: super-secret-jwt-key
    depends_on:
      - db
    command: >
      sh -c "
        npx prisma generate &&
        (npx prisma migrate deploy || npx prisma db push) &&
        node dist/src/main.js
      "

volumes:
  postgres_data:
